// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



function sumEvenFib(){
  var fibo = [1,2];
  var sum = 0;
  var i = 2;
  while (fibo[i-1] + fibo[i-2] <= 4000000){
    fibo[i] = fibo[i-1] + fibo[i-2];
    i++;
    }
  for (var j in fibo){
    if(fibo[j] % 2 === 0){
      sum += fibo[j];
    }
  }
  console.log(sum);
}











// FIBONACCI
//Write a function fib() that takes an integer 'n' and returns the 'nth' fibonacci number

function fib(n){
  var seq = [];
  seq[0] = 0;
  seq[1] = 1;
  for(var i=2; i<11; i++){
    seq[i] = seq[i-2] + seq[i-1];
  }
  console.log(seq[n]);
}
